const actions = {
  SET_TODO: 'SET_TODO',
  SET_DONE_TODO: 'SET_DONE_TODO',
  REMOVE_TODO_FROM_DONES: 'REMOVE_TODO_FROM_DONES',
  DELETE_TODO: 'DELETE_TODO',
  EDIT_TODO_TITLE: 'EDIT_TODO_TITLE',
}

export default actions
